import { StyleSheet, Dimensions } from "react-native"

const { width } = Dimensions.get("window")

export const styles = StyleSheet.create({
  section: {
    backgroundColor: "#ffffff",
    marginVertical: 8,
  },
  header: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 18,
    paddingHorizontal: 20,
  },
  sectionTitle: {
    fontSize: 22,
    fontWeight: "800",
    color: "#1f2937",
    letterSpacing: 0.3,
  },
  seeAllButton: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 10,
    backgroundColor: "#fef2f8",
  },
  seeAllText: {
    fontSize: 14,
    fontWeight: "700",
    color: "#db2777",
    marginRight: 4,
    letterSpacing: 0.2,
  },
  loadingContainer: {
    paddingVertical: 48,
    alignItems: "center",
    marginHorizontal: 20,
  },
  loadingText: {
    marginTop: 16,
    color: "#9ca3af",
    fontSize: 14,
    fontWeight: "600",
  },
  emptyContainer: {
    paddingVertical: 48,
    alignItems: "center",
    backgroundColor: "#f9fafb",
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "#e5e7eb",
    marginHorizontal: 20,
  },
  emptyText: {
    marginTop: 16,
    fontSize: 16,
    fontWeight: "700",
    color: "#1f2937",
    letterSpacing: 0.2,
  },
  emptySubtext: {
    marginTop: 6,
    fontSize: 13,
    color: "#9ca3af",
    fontWeight: "500",
  },
  scrollContent: {
    paddingLeft: 20,
    paddingRight: 4,
  },
  card: {
    width: width - 40,
    backgroundColor: "#ffffff",
    borderRadius: 18,
    padding: 18,
    marginBottom: 8,
    marginRight: 16,
    borderWidth: 1,
    borderColor: "#e5e7eb",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.1,
    shadowRadius: 10,
    elevation: 4,
  },
  cardHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 12,
  },
  badge: {
    borderRadius: 14,
    paddingHorizontal: 12,
    paddingVertical: 6,
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  badgeText: {
    fontSize: 11,
    fontWeight: "800",
    color: "#ffffff",
    letterSpacing: 0.4,
  },
  dateText: {
    fontSize: 12,
    color: "#9ca3af",
    fontWeight: "700",
  },
  cardTitle: {
    fontSize: 16,
    fontWeight: "800",
    color: "#1f2937",
    marginBottom: 8,
    lineHeight: 24,
    letterSpacing: 0.2,
  },
  cardDescription: {
    fontSize: 13,
    color: "#6b7280",
    lineHeight: 20,
    marginBottom: 12,
    fontWeight: "500",
  },
  highlightBanner: {
    backgroundColor: "#fef2f2",
    borderRadius: 12,
    padding: 12,
    flexDirection: "row",
    alignItems: "center",
    borderWidth: 1,
    borderColor: "#fecaca",
    marginTop: 8,
    gap: 8,
  },
  highlightText: {
    fontSize: 14,
    fontWeight: "800",
    color: "#dc2626",
    letterSpacing: 0.2,
  },
})