import { StyleSheet } from "react-native"
import { COLORS } from "../utils/constants"

export const commonStyles = StyleSheet.create({
  container: {
    flex: 1,
  },
  gradient: {
    flex: 1,
  },
  flex: {
    flex: 1,
  },
  scrollContent: {
    flexGrow: 1,
    justifyContent: "center",
  },
  content: {
    flex: 1,
    justifyContent: "center",
    padding: 16,
  },
  card: {
    backgroundColor: COLORS.BACKGROUND,
    borderRadius: 14,
    padding: 20,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.12,
    shadowRadius: 10,
    elevation: 5,
  },
  header: {
    alignItems: "center",
    marginBottom: 18,
  },
  logoContainer: {
    alignItems: "center",
  },
  logoCircle: {
    width: 60,
    height: 60,
    borderRadius: 30,
    backgroundColor: "#f5e6ed",
    justifyContent: "center",
    alignItems: "center",
    marginTop: 10,
    overflow: "hidden",
  },
  logoImage: {
    width: 54,
    height: 54,
    borderRadius: 27,
  },
  brandText: {
    fontSize: 24,
    color: COLORS.TEXT_PRIMARY,
    letterSpacing: 0.5,
    fontFamily: "LobsterTwo-Italic",
  },
  welcomeSection: {
    alignItems: "center",
    marginBottom: 16,
  },
  welcomeTitle: {
    fontSize: 20,
    fontWeight: "600",
    color: COLORS.TEXT_PRIMARY,
    marginBottom: 4,
    letterSpacing: 0.4,
    fontFamily: "Poppins-SemiBold",
  },
  welcomeSubtitle: {
    fontSize: 13,
    color: COLORS.TEXT_SECONDARY,
    textAlign: "center",
    lineHeight: 18,
    fontFamily: "Inter-Variable",
    fontWeight: "500",
  },
  progressContainer: {
    marginBottom: 16,
  },
  progressBar: {
    height: 5,
    backgroundColor: "#f0f0f0",
    borderRadius: 3,
    overflow: "hidden",
    marginBottom: 6,
  },
  progressFill: {
    height: "100%",
    backgroundColor: COLORS.PRIMARY,
    borderRadius: 3,
  },
  progressText: {
    fontSize: 11,
    color: COLORS.TEXT_SECONDARY,
    textAlign: "center",
    fontWeight: "500",
    fontFamily: "Inter-Variable",
  },
  form: {
    width: "100%",
  },
  inputGroup: {
    marginBottom: 12,
  },
  inputLabel: {
    fontSize: 12,
    color: "#333333",
    marginBottom: 6,
    fontWeight: "600",
    letterSpacing: 0.3,
    fontFamily: "Inter-Variable",
  },
  input: {
    borderWidth: 2,
    borderColor: COLORS.BORDER,
    borderRadius: 9,
    padding: 11,
    fontSize: 14,
    backgroundColor: COLORS.BACKGROUND,
    color: COLORS.TEXT_PRIMARY,
    fontWeight: "500",
    fontFamily: "Inter-Variable",
  },
  buttonRow: {
    flexDirection: "row",
    gap: 10,
    marginTop: 2,
  },
  backButton: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: COLORS.BACKGROUND,
    borderWidth: 2,
    borderColor: COLORS.PRIMARY,
    borderRadius: 9,
    padding: 12,
  },
  backButtonText: {
    color: COLORS.PRIMARY,
    fontSize: 15,
    fontWeight: "700",
    marginLeft: 6,
    letterSpacing: 0.4,
    fontFamily: "Inter-Variable",
  },
  nextButton: {
    flex: 1,
    backgroundColor: COLORS.PRIMARY,
    borderRadius: 9,
    padding: 12,
    alignItems: "center",
    justifyContent: "center",
    shadowColor: COLORS.PRIMARY,
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.25,
    shadowRadius: 6,
    elevation: 4,
  },
  nextButtonDisabled: {
    backgroundColor: COLORS.PRIMARY_LIGHT,
    shadowOpacity: 0.1,
  },
  nextButtonText: {
    color: COLORS.BACKGROUND,
    fontSize: 15,
    fontWeight: "700",
    letterSpacing: 0.6,
    fontFamily: "Inter-Variable",
  },
  loginContainer: {
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    marginTop: 12,
  },
  loginText: {
    fontSize: 13,
    color: COLORS.TEXT_SECONDARY,
    fontFamily: "Inter-Variable",
  },
  loginLink: {
    fontSize: 13,
    color: COLORS.PRIMARY,
    fontWeight: "700",
    fontFamily: "Inter-Variable",
  },
  linkDisabled: {
    color: COLORS.PRIMARY_LIGHT,
  },
})
