import { StyleSheet } from "react-native"

export const styles = StyleSheet.create({
  section: {
    paddingHorizontal: 20,
    paddingVertical: 24,
    backgroundColor: "#fafbfc",
  },
  card: {
    background: "linear-gradient(135deg, #db2777 0%, #be185d 100%)",
    backgroundColor: "#db2777",
    borderRadius: 24,
    overflow: "hidden",
    shadowColor: "#db2777",
    shadowOffset: { width: 0, height: 12 },
    shadowOpacity: 0.35,
    shadowRadius: 16,
    elevation: 10,
  },
  cardContent: {
    paddingVertical: 32,
    paddingHorizontal: 24,
    alignItems: "center",
  },
  iconContainer: {
    width: 64,
    height: 64,
    borderRadius: 20,
    backgroundColor: "rgba(255, 255, 255, 0.2)",
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 16,
    borderWidth: 2,
    borderColor: "rgba(255, 255, 255, 0.3)",
  },
  title: {
    fontSize: 28,
    fontWeight: "800",
    color: "#ffffff",
    marginBottom: 12,
    textAlign: "center",
    letterSpacing: 0.3,
  },
  subtitle: {
    fontSize: 15,
    color: "#fce7f3",
    marginBottom: 28,
    textAlign: "center",
    lineHeight: 24,
    fontWeight: "600",
  },
  button: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#ffffff",
    paddingVertical: 16,
    paddingHorizontal: 36,
    borderRadius: 16,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.25,
    shadowRadius: 12,
    elevation: 6,
    minWidth: 200,
  },
  buttonText: {
    fontSize: 16,
    fontWeight: "800",
    color: "#db2777",
    marginRight: 10,
    letterSpacing: 0.3,
  },
})