import { StyleSheet } from "react-native"

export const loginScreenStyles = StyleSheet.create({
  container: {
    flex: 1,
  },
  gradient: {
    flex: 1,
  },
  flex: {
    flex: 1,
  },
  scrollContent: {
    flexGrow: 1,
    justifyContent: "center",
  },
  content: {
    flex: 1,
    justifyContent: "center",
    padding: 16,
  },
  card: {
    backgroundColor: "#ffffff",
    borderRadius: 14,
    padding: 20,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.12,
    shadowRadius: 10,
    elevation: 5,
  },
  header: {
    alignItems: "center",
    marginBottom: 18,
  },
  logoContainer: {
    alignItems: "center",
  },
  logoCircle: {
    width: 60,
    height: 60,
    borderRadius: 30,
    backgroundColor: "#f5e6ed",
    justifyContent: "center",
    alignItems: "center",
    marginTop: 10,
    overflow: "hidden",
  },
  logoImage: {
    width: 54,
    height: 54,
    borderRadius: 27,
  },
  brandText: {
    fontSize: 24,
    color: "#1a1a1a",
    letterSpacing: 0.5,
    fontFamily: "LobsterTwo-Italic",
  },
  welcomeSection: {
    alignItems: "center",
    marginBottom: 18,
  },
  welcomeTitle: {
    fontSize: 20,
    fontWeight: "600",
    color: "#1a1a1a",
    marginBottom: 4,
    letterSpacing: 0.4,
    fontFamily: "Poppins-SemiBold",
  },
  welcomeSubtitle: {
    fontSize: 13,
    color: "#666666",
    textAlign: "center",
    lineHeight: 18,
    fontFamily: "Inter-Variable",
    fontWeight: "500",
  },
  form: {
    width: "100%",
  },
  inputGroup: {
    marginBottom: 12,
  },
  inputLabel: {
    fontSize: 12,
    color: "#333333",
    marginBottom: 6,
    fontWeight: "600",
    letterSpacing: 0.3,
    fontFamily: "Inter-Variable",
  },
  input: {
    borderWidth: 2,
    borderColor: "#e0e0e0",
    borderRadius: 9,
    padding: 11,
    fontSize: 14,
    backgroundColor: "#ffffff",
    color: "#1a1a1a",
    fontWeight: "500",
    fontFamily: "Inter-Variable",
  },
  inputError: {
    borderColor: "#ff5252",
    backgroundColor: "#ffebee",
  },
  errorText: {
    fontSize: 11,
    color: "#ff5252",
    marginTop: 4,
    fontWeight: "500",
    fontFamily: "Inter-Variable",
  },
  formOptions: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 16,
    marginTop: 4,
  },
  rememberMeContainer: {
    flexDirection: "row",
    alignItems: "center",
  },
  checkboxContainer: {
    marginRight: 8,
    padding: 2,
  },
  checkbox: {
    width: 18,
    height: 18,
    borderWidth: 2,
    borderColor: "#e91e63",
    borderRadius: 5,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#ffffff",
  },
  checkboxChecked: {
    backgroundColor: "#e91e63",
    borderColor: "#e91e63",
  },
  checkmark: {
    color: "#ffffff",
    fontSize: 11,
    fontWeight: "700",
  },
  rememberMeText: {
    fontSize: 12,
    color: "#333333",
    fontWeight: "500",
    fontFamily: "Inter-Variable",
  },
  forgotPassword: {
    fontSize: 12,
    color: "#e91e63",
    fontWeight: "600",
    padding: 2,
    fontFamily: "Inter-Variable",
  },
  signInButton: {
    backgroundColor: "#e91e63",
    borderRadius: 9,
    padding: 12,
    alignItems: "center",
    marginBottom: 14,
    marginTop: 4,
    shadowColor: "#e91e63",
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.25,
    shadowRadius: 6,
    elevation: 4,
  },
  signInButtonDisabled: {
    backgroundColor: "#f8bbd0",
    shadowOpacity: 0.1,
  },
  signInButtonText: {
    color: "#ffffff",
    fontSize: 15,
    fontWeight: "700",
    letterSpacing: 0.6,
    fontFamily: "Inter-Variable",
  },
  loadingContainer: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
  },
  loadingText: {
    color: "#ffffff",
    fontSize: 15,
    fontWeight: "700",
    marginLeft: 8,
    fontFamily: "Inter-Variable",
  },
  signUpContainer: {
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    marginTop: 12,
  },
  signUpText: {
    fontSize: 13,
    color: "#666666",
    fontFamily: "Inter-Variable",
  },
  signUpLink: {
    fontSize: 13,
    color: "#e91e63",
    fontWeight: "700",
    fontFamily: "Inter-Variable",
  },
  linkDisabled: {
    color: "#f8bbd0",
  },
  passwordContainer: {
    flexDirection: "row",
    alignItems: "center",
    borderWidth: 2,
    borderColor: "#e0e0e0",
    borderRadius: 9,
    backgroundColor: "#ffffff",
  },
  passwordContainerError: {
    borderColor: "#ff5252",
    backgroundColor: "#ffebee",
  },
  passwordInput: {
    flex: 1,
    padding: 11,
    fontSize: 14,
    color: "#1a1a1a",
    fontWeight: "500",
    fontFamily: "Inter-Variable",
  },
  eyeIcon: {
    padding: 10,
  },
  eyeIconText: {
    fontSize: 14,
  },
})