import { StyleSheet } from "react-native"

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#ffffff",
  },
  centerContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    padding: 20,
  },
  loadingText: {
    marginTop: 12,
    fontSize: 16,
    color: "#6b7280",
  },
  loginPromptText: {
    fontSize: 18,
    color: "#4b5563",
    marginBottom: 20,
    textAlign: "center",
  },
  loginButton: {
    backgroundColor: "#db2777",
    borderRadius: 8,
    paddingVertical: 14,
    paddingHorizontal: 40,
  },
  loginButtonText: {
    color: "#ffffff",
    fontSize: 16,
    fontWeight: "700",
  },
  scrollView: {
    flex: 1,
  },
  header: {
    backgroundColor: "rgba(255, 255, 255, 0.95)",
    paddingHorizontal: 20,
    paddingVertical: 16,
    borderBottomWidth: 1,
    borderBottomColor: "#f9a8d4",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  backButton: {
    padding: 8,
  },
  backButtonText: {
    fontSize: 16,
    fontWeight: "600",
    color: "#db2777",
  },
  notificationButton: {
    position: 'relative',
    padding: 8,
  },
  content: {
    flex: 1,
    paddingHorizontal: 20,
    paddingVertical: 20,
  },
  userInfoSection: {
    backgroundColor: "#f0f9ff",
    borderRadius: 12,
    padding: 16,
    marginBottom: 20,
    borderLeftWidth: 4,
    borderLeftColor: "#db2777",
  },
  userInfoHeader: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 12,
  },
  userInfoTitle: {
    fontSize: 12,
    fontWeight: "600",
    color: "#6b7280",
    marginBottom: 4,
    textTransform: "uppercase",
  },
  userInfoName: {
    fontSize: 18,
    fontWeight: "700",
    color: "#000000",
  },
  userInfoDetails: {
    gap: 8,
  },
  userInfoRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  userInfoDetail: {
    fontSize: 14,
    color: "#4b5563",
  },
  section: {
    marginBottom: 30,
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: "700",
    color: "#000000",
    marginBottom: 20,
  },
  emptyState: {
    alignItems: "center",
    padding: 40,
  },
  emptyStateText: {
    marginTop: 12,
    fontSize: 16,
    color: "#9ca3af",
  },
  serviceRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingVertical: 15,
    backgroundColor: "#FFE5F0",
    paddingHorizontal: 15,
    marginBottom: 8,
    borderRadius: 8,
  },
  addOnRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingVertical: 15,
    backgroundColor: "#FFE5F0",
    paddingHorizontal: 15,
    marginBottom: 8,
    borderRadius: 8,
  },
  serviceInfo: {
    flex: 1,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginRight: 15,
  },
  serviceNameContainer: {
    flex: 1,
  },
  serviceName: {
    fontSize: 16,
    fontWeight: "500",
    color: "#000000",
  },
  serviceSubtitle: {
    fontSize: 12,
    fontWeight: "400",
    color: "#4b5563",
    marginTop: 2,
  },
  servicePrice: {
    fontSize: 16,
    fontWeight: "600",
    color: "#000000",
    marginLeft: 10,
  },
  checkbox: {
    width: 24,
    height: 24,
    borderWidth: 2,
    borderColor: "#db2777",
    borderRadius: 4,
    justifyContent: "center",
    alignItems: "center",
  },
  checkboxSelected: {
    backgroundColor: "#db2777",
  },
  checkmark: {
    color: "#ffffff",
    fontSize: 14,
    fontWeight: "bold",
  },
  quantityControls: {
    flexDirection: "row",
    alignItems: "center",
    gap: 15,
  },
  quantityButton: {
    width: 30,
    height: 30,
    borderRadius: 15,
    backgroundColor: "#f3f4f6",
    justifyContent: "center",
    alignItems: "center",
  },
  quantityButtonText: {
    fontSize: 18,
    fontWeight: "600",
    color: "#db2777",
  },
  quantityText: {
    fontSize: 16,
    fontWeight: "600",
    color: "#000000",
    minWidth: 20,
    textAlign: "center",
  },
  totalFooter: {
    backgroundColor: "#db2777",
    paddingHorizontal: 20,
    paddingVertical: 20,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  totalLabel: {
    fontSize: 18,
    fontWeight: "700",
    color: "#ffffff",
  },
  totalAmount: {
    fontSize: 24,
    fontWeight: "700",
    color: "#ffffff",
  },
  confirmButtonContainer: {
    paddingHorizontal: 0,
    paddingVertical: 20,
  },
  confirmButtonFull: {
    backgroundColor: "#db2777",
    borderRadius: 8,
    paddingVertical: 16,
    alignItems: "center",
  },
  confirmButtonDisabled: {
    opacity: 0.6,
  },
  confirmButtonFullText: {
    fontSize: 16,
    fontWeight: "700",
    color: "#ffffff",
  },
  loadingContainer: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  orderSummary: {
    backgroundColor: "#FFE5F0",
    borderRadius: 8,
    padding: 20,
    marginBottom: 30,
  },
  orderNumber: {
    fontSize: 14,
    fontWeight: "600",
    color: "#000000",
    marginBottom: 15,
  },
  orderItem: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 8,
  },
  orderItemName: {
    fontSize: 14,
    color: "#000000",
    flex: 1,
    paddingRight: 10,
  },
  orderItemPrice: {
    fontSize: 14,
    fontWeight: "600",
    color: "#000000",
  },
  orderTotal: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginTop: 10,
    paddingTop: 10,
    borderTopWidth: 1,
    borderTopColor: "#f9a8d4",
  },
  orderTotalLabel: {
    fontSize: 16,
    fontWeight: "700",
    color: "#000000",
  },
  orderTotalAmount: {
    fontSize: 16,
    fontWeight: "700",
    color: "#000000",
  },
  calendar: {
    backgroundColor: "#FFE5F0",
    borderRadius: 8,
    padding: 20,
  },
  calendarHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 20,
  },
  calendarArrow: {
    fontSize: 18,
    fontWeight: "600",
    color: "#000000",
    padding: 10,
  },
  calendarMonth: {
    fontSize: 16,
    fontWeight: "700",
    color: "#000000",
  },
  calendarDaysHeader: {
    flexDirection: "row",
    justifyContent: "space-around",
    marginBottom: 10,
  },
  calendarDayName: {
    width: 40,
    textAlign: "center",
    fontSize: 12,
    fontWeight: "600",
    color: "#4b5563",
  },
  calendarGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
  },
  calendarDay: {
    width: "14.28%",
    aspectRatio: 1,
    justifyContent: "center",
    alignItems: "center",
    marginVertical: 2,
  },
  calendarDayOtherMonth: {
    opacity: 0.3,
  },
  calendarDayDisabled: {
    opacity: 0.3,
  },
  calendarDaySelected: {
    backgroundColor: "#db2777",
    borderRadius: 20,
  },
  calendarDayText: {
    fontSize: 14,
    color: "#000000",
  },
  calendarDayTextOtherMonth: {
    color: "#9ca3af",
  },
  calendarDayTextDisabled: {
    color: "#d1d5db",
  },
  calendarDayTextSelected: {
    color: "#ffffff",
    fontWeight: "700",
  },
  timePicker: {
    backgroundColor: "#FFE5F0",
    borderRadius: 8,
    padding: 20,
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    height: 150,
  },
  timeColumn: {
    width: 60,
    height: 120,
  },
  timeScroll: {
    flex: 1,
  },
  timeScrollContent: {
    paddingVertical: 40,
  },
  timeOption: {
    height: 40,
    justifyContent: "center",
    alignItems: "center",
  },
  timeText: {
    fontSize: 18,
    color: "#9ca3af",
  },
  timeTextSelected: {
    fontSize: 24,
    fontWeight: "700",
    color: "#000000",
  },
  timeSeparator: {
    fontSize: 24,
    fontWeight: "700",
    color: "#000000",
    marginHorizontal: 10,
  },
  timePeriodContainer: {
    flex: 1,
    justifyContent: "center",
  },
  paymentOption: {
    backgroundColor: "#FFE5F0",
    borderRadius: 8,
    padding: 16,
    marginBottom: 10,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    borderWidth: 2,
    borderColor: "transparent",
  },
  paymentOptionSelected: {
    borderColor: "#db2777",
    backgroundColor: "#ffffff",
  },
  paymentOptionDisabled: {
    opacity: 0.5,
  },
  paymentText: {
    fontSize: 16,
    color: "#000000",
  },
  paymentTextSelected: {
    fontWeight: "600",
  },
  paymentTextDisabled: {
    color: "#9ca3af",
  },
  paymentCheckbox: {
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: "#db2777",
    justifyContent: "center",
    alignItems: "center",
  },
  errorContainer: {
    backgroundColor: "#fee2e2",
    borderRadius: 8,
    padding: 12,
    marginBottom: 16,
    borderLeftWidth: 4,
    borderLeftColor: "#ef4444",
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  errorText: {
    color: "#dc2626",
    fontSize: 14,
    fontWeight: "500",
    flex: 1,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0, 0, 0, 0.5)",
    justifyContent: "center",
    alignItems: "center",
    padding: 20,
  },
  modalContent: {
    backgroundColor: "#ffffff",
    borderRadius: 20,
    padding: 40,
    alignItems: "center",
    width: "100%",
    maxWidth: 400,
  },
  successIconContainer: {
    marginBottom: 30,
  },
  successIconOuter: {
    width: 100,
    height: 100,
    borderRadius: 50,
    backgroundColor: "#d1fae5",
    justifyContent: "center",
    alignItems: "center",
  },
  successIconInner: {
    width: 70,
    height: 70,
    borderRadius: 35,
    backgroundColor: "#10b981",
    justifyContent: "center",
    alignItems: "center",
  },
  successCheckmark: {
    color: "#ffffff",
    fontSize: 40,
    fontWeight: "bold",
  },
  congratsText: {
    fontSize: 24,
    fontWeight: "700",
    color: "#000000",
    marginBottom: 15,
    textAlign: "center",
  },
  successMessage: {
    fontSize: 14,
    color: "#6b7280",
    textAlign: "center",
    lineHeight: 20,
    marginBottom: 30,
  },
  viewHomeButton: {
    backgroundColor: "#ec4899",
    borderRadius: 8,
    paddingVertical: 14,
    paddingHorizontal: 40,
    width: "100%",
  },
  viewHomeButtonText: {
    color: "#ffffff",
    fontSize: 16,
    fontWeight: "700",
    textAlign: "center",
  },
  timeTextOccupied: {
    color: "#ef4444",
    textDecorationLine: "line-through",
  },
  loadingSlotsText: {
    fontSize: 14,
    color: "#6b7280",
    marginBottom: 10,
    fontStyle: "italic",
  },
  selectedDateText: {
    fontSize: 14,
    color: "#4b5563",
    marginBottom: 10,
  },
  occupiedWarning: {
    backgroundColor: "#fee2e2",
    borderRadius: 8,
    padding: 12,
    marginBottom: 12,
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    borderLeftWidth: 4,
    borderLeftColor: "#ef4444",
  },
  occupiedWarningText: {
    color: "#dc2626",
    fontSize: 14,
    fontWeight: "500",
    flex: 1,
  },
  // Confirmation Modal Styles
  warningIconContainer: {
    marginBottom: 25,
  },
  warningIconOuter: {
    width: 100,
    height: 100,
    borderRadius: 50,
    backgroundColor: "#fef3c7",
    justifyContent: "center",
    alignItems: "center",
  },
  warningIconInner: {
    width: 70,
    height: 70,
    borderRadius: 35,
    backgroundColor: "#f59e0b",
    justifyContent: "center",
    alignItems: "center",
  },
  warningTitle: {
    fontSize: 24,
    fontWeight: "700",
    color: "#000000",
    marginBottom: 12,
    textAlign: "center",
  },
  warningMessage: {
    fontSize: 14,
    color: "#6b7280",
    textAlign: "center",
    lineHeight: 20,
    marginBottom: 20,
  },
  policyContainer: {
    width: "100%",
    backgroundColor: "#fef3c7",
    borderRadius: 12,
    padding: 16,
    marginBottom: 25,
  },
  policyItem: {
    flexDirection: "row",
    alignItems: "flex-start",
    marginBottom: 12,
    gap: 10,
  },
  policyText: {
    flex: 1,
    fontSize: 13,
    color: "#4b5563",
    lineHeight: 18,
  },
  policyTextBold: {
    fontWeight: "700",
    color: "#000000",
  },
  modalButtons: {
    flexDirection: "row",
    width: "100%",
    gap: 12,
  },
  cancelButton: {
    flex: 1,
    backgroundColor: "#f3f4f6",
    borderRadius: 8,
    paddingVertical: 14,
    alignItems: "center",
    borderWidth: 1,
    borderColor: "#d1d5db",
  },
  cancelButtonText: {
    color: "#4b5563",
    fontSize: 16,
    fontWeight: "600",
  },
  agreeButton: {
    flex: 1,
    backgroundColor: "#db2777",
    borderRadius: 8,
    paddingVertical: 14,
    alignItems: "center",
  },
  agreeButtonText: {
    color: "#ffffff",
    fontSize: 16,
    fontWeight: "700",
  },
})