import { StyleSheet, Dimensions, Platform, StatusBar } from "react-native"

const { width, height } = Dimensions.get("window")

// Get the status bar height for proper padding
const STATUSBAR_HEIGHT = Platform.OS === 'ios' ? 44 : StatusBar.currentHeight || 0

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#ffffff",
  },
  scrollView: {
    flex: 1,
  },
  headerContainer: {
    backgroundColor: "#ffffff",
    borderBottomWidth: 0,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 8,
    elevation: 4,
    paddingTop: Platform.OS === 'ios' ? 0 : 8,
  },
  header: {
    paddingTop: 34,
    paddingHorizontal: 20,
    paddingVertical: 8,
  },
  headerContent: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  logo: {
    flexDirection: "row",
    alignItems: "center",
  },
  logoImageContainer: {
    width: 40,
    height: 40,
    borderRadius: 20,
    overflow: "hidden",
    marginRight: 12,
    borderWidth: 2,
    borderColor: "#db2777",
    backgroundColor: "#f3e8ff",
  },
  logoImage: {
    width: "100%",
    height: "100%",
  },
  logoTitle: {
    fontSize: 18,
    fontWeight: "800",
    color: "#1f2937",
    letterSpacing: 0.3,
    fontFamily: "LobsterTwo-Italic",
  },
  rightButtons: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  notificationButton: {
    position: "relative",
    padding: 10,
    borderRadius: 12,
    backgroundColor: "#f3f4f6",
    marginRight: 4,
  },
  notificationBadge: {
    position: "absolute",
    top: 4,
    right: 4,
    backgroundColor: "#ef4444",
    borderRadius: 12,
    minWidth: 20,
    height: 20,
    justifyContent: "center",
    alignItems: "center",
    paddingHorizontal: 4,
    borderWidth: 2,
    borderColor: "#ffffff",
  },
  notificationBadgeText: {
    color: "#fff",
    fontSize: 11,
    fontWeight: "800",
  },
  hamburgerButton: {
    padding: 10,
    borderRadius: 12,
    backgroundColor: "#f3f4f6",
  },
  hamburgerLine: {
    width: 22,
    height: 2.5,
    backgroundColor: "#1f2937",
    marginVertical: 3.5,
    borderRadius: 2,
  },
  contentContainer: {
    paddingBottom: 40,
  },

  // Welcome Section
  welcomeSection: {
    paddingHorizontal: 20,
    paddingTop: 28,
    paddingBottom: 24,
    backgroundColor: "#ffffff",
    borderBottomLeftRadius: 24,
    borderBottomRightRadius: 24,
    marginBottom: 16,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.04,
    shadowRadius: 8,
    elevation: 2,
  },
  greetingText: {
    fontSize: 15,
    color: "#9ca3af",
    marginBottom: 6,
    fontWeight: "500",
    letterSpacing: 0.3,
  },
  userName: {
    fontSize: 32,
    fontWeight: "800",
    color: "#1f2937",
    marginBottom: 2,
    letterSpacing: -0.5,
  },

  // Quick Actions Section
  quickActionsSection: {
    paddingHorizontal: 20,
    paddingVertical: 24,
    backgroundColor: "#fafbfc",
  },
  sectionTitleText: {
    fontSize: 20,
    fontWeight: "800",
    color: "#1f2937",
    marginBottom: 16,
    letterSpacing: 0.3,
  },
  quickActionsGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "space-between",
    gap: 12,
  },
  quickActionCard: {
    width: (width - 52) / 2,
    aspectRatio: 1,
    borderRadius: 20,
    padding: 16,
    justifyContent: "center",
    alignItems: "center",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.12,
    shadowRadius: 12,
    elevation: 5,
  },
  quickActionText: {
    fontSize: 13,
    fontWeight: "700",
    color: "#ffffff",
    marginTop: 14,
    textAlign: "center",
    letterSpacing: 0.2,
  },

  // Announcements Section
  announcementsSection: {
    paddingHorizontal: 20,
    paddingVertical: 24,
    backgroundColor: "#ffffff",
  },
  sectionTitleRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 16,
  },
  seeAllText: {
    fontSize: 14,
    fontWeight: "700",
    color: "#db2777",
  },
  announcementCard: {
    width: width * 0.8,
    backgroundColor: "#ffffff",
    borderRadius: 16,
    padding: 16,
    marginRight: 12,
    borderWidth: 1,
    borderColor: "#e5e7eb",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 3,
  },
  announcementHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 10,
  },
  announcementBadge: {
    borderRadius: 12,
    paddingHorizontal: 12,
    paddingVertical: 6,
    backgroundColor: "#db2777",
  },
  announcementBadgeText: {
    fontSize: 11,
    fontWeight: "700",
    color: "#ffffff",
    letterSpacing: 0.5,
  },
  announcementDate: {
    fontSize: 12,
    color: "#9ca3af",
    fontWeight: "600",
  },
  announcementTitle: {
    fontSize: 16,
    fontWeight: "800",
    color: "#1f2937",
    marginBottom: 8,
    lineHeight: 22,
    letterSpacing: 0.2,
  },
  announcementDescription: {
    fontSize: 13,
    color: "#6b7280",
    lineHeight: 20,
    marginBottom: 10,
    fontWeight: "500",
  },
  discountBanner: {
    backgroundColor: "#fef2f2",
    borderRadius: 12,
    padding: 10,
    alignItems: "center",
    borderWidth: 1,
    borderColor: "#fecaca",
    marginTop: 8,
  },
  discountText: {
    fontSize: 14,
    fontWeight: "800",
    color: "#dc2626",
    letterSpacing: 0.2,
  },

  // Services Section
  servicesSection: {
    paddingHorizontal: 20,
    paddingVertical: 24,
    backgroundColor: "#fafbfc",
  },
  servicesGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "space-between",
    gap: 12,
  },
  serviceCard: {
    width: (width - 52) / 2,
    backgroundColor: "#ffffff",
    borderRadius: 18,
    padding: 16,
    borderWidth: 1,
    borderColor: "#e5e7eb",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.06,
    shadowRadius: 6,
    elevation: 2,
    alignItems: "center",
    justifyContent: "center",
  },
  serviceIcon: {
    width: 80,
    height: 80,
    borderRadius: 16,
    marginBottom: 12,
  },
  serviceTitle: {
    fontSize: 15,
    fontWeight: "800",
    color: "#1f2937",
    marginBottom: 6,
    textAlign: "center",
    letterSpacing: 0.2,
  },
  serviceDescription: {
    fontSize: 12,
    color: "#9ca3af",
    textAlign: "center",
    lineHeight: 18,
    fontWeight: "500",
  },

  // CTA Section
  ctaSection: {
    paddingHorizontal: 20,
    paddingVertical: 24,
    backgroundColor: "#ffffff",
  },
  ctaCard: {
    backgroundColor: "#db2777",
    borderRadius: 24,
    padding: 28,
    alignItems: "center",
    shadowColor: "#db2777",
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.25,
    shadowRadius: 16,
    elevation: 8,
    overflow: "hidden",
  },
  ctaTitle: {
    fontSize: 26,
    fontWeight: "800",
    color: "#ffffff",
    marginBottom: 10,
    textAlign: "center",
    letterSpacing: 0.2,
  },
  ctaSubtitle: {
    fontSize: 15,
    color: "#fce7f3",
    marginBottom: 24,
    textAlign: "center",
    lineHeight: 24,
    fontWeight: "600",
  },
  ctaButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#ffffff",
    paddingVertical: 14,
    paddingHorizontal: 32,
    borderRadius: 14,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.15,
    shadowRadius: 8,
    elevation: 4,
    minWidth: 200,
  },
  ctaButtonText: {
    fontSize: 16,
    fontWeight: "800",
    color: "#db2777",
    marginRight: 8,
    letterSpacing: 0.2,
  },

  // Side Menu
  menuOverlay: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: "rgba(0, 0, 0, 0.6)",
    zIndex: 98,
  },
  sideMenu: {
    position: "absolute",
    top: 0,
    left: 0,
    width: width * 0.8,
    height: "100%",
    backgroundColor: "#ffffff",
    paddingTop: Platform.OS === 'ios' ? 60 : STATUSBAR_HEIGHT + 20,
    shadowColor: "#000",
    shadowOffset: { width: 2, height: 0 },
    shadowOpacity: 0.3,
    shadowRadius: 12,
    elevation: 10,
    zIndex: 99,
  },
  menuHeader: {
    paddingHorizontal: 20,
    paddingVertical: 24,
    borderBottomWidth: 1,
    borderBottomColor: "#e5e7eb",
  },
  menuTitle: {
    fontSize: 28,
    fontWeight: "800",
    color: "#1f2937",
    letterSpacing: 0.3,
  },
  menuItems: {
    paddingTop: 8,
  },
  menuItem: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 20,
    paddingVertical: 16,
    borderBottomWidth: 1,
    borderBottomColor: "#f9fafb",
  },
  menuItemText: {
    fontSize: 15,
    fontWeight: "700",
    color: "#1f2937",
    letterSpacing: 0.3,
  },
})

export { width, height, STATUSBAR_HEIGHT }